base/config/routes.rb
Stripemetrics::Application.routes.draw do
	
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin'                  => 'sessions#new',     :as => :signin
  match '/signout'                 => 'sessions#destroy', :as => :signout
  match '/auth/failure'            => 'sessions#failure'

  # =============== HOME ============================================
  match 'quickstart'          => 'home#quickstart',:as => :quickstart
  match 'faq'                 => 'home#faq',       :as => :faq
  match 'about'               => 'home#about',     :as => :about

  # =============== USER ============================================
  match 'account'              => 'users#edit',               :as => :account
  match 'cancel'               => 'users#destroy',            :as => :cancel
  match '/users/update'        => 'users#update',             :as => :user_update
  match 'upgrade_from_trial'   => 'users#upgrade_from_trial', :as => :upgrade_from_trial
  match 'update_plan'          => 'users#update_plan',        :as => :update_plan

  # =============== PLANS ===========================================
  match 'plans'                => 'plans#index',   :as => :pricing
  match 'upgrading'            => 'plans#index_for_upgrading',   :as => :upgrading

  # =============== RESOURCES ============================================
  get '/trends/:id/source',  to: 'trends#source'
  resources :trends, :only => [:show, :index]

  # =============== OTHER ============================================
  match 'dashboard'        => 'dashboard#index',:as => :dashboard
  match 'cohort'           => 'cohorts#index',:as => :cohort
  match 'status'           => 'imports#index',:as => :status

  # match 'jobs'                     => 'jobs#index',      :as => :jobs      
  # match 'jobs/:action'             => 'jobs#action'

  root :to => "home#quickstart"
  resources :users, :only => [:index, :show, :edit, :update ]

  mount Resque::Server, :at => "/rescousse"  

end

base/app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps::Created::Short
  include Billable

  MAX_IMPORTS      = 50
  # John and Patrick first started working on Stripe in early 2010.
  BEGINING_OF_TIME = Time.parse('01/01/2010')

  field :provider, type: String
  field :uid,      type: String
  field :email,    type: String
  field :password_hash, :type => String
  field :livemode, type: Boolean
  field :api_token,    type: String
  field :token,    type: String
  field :token_expires, type: Boolean
  field :admin, type: Boolean, default: false

  # validates_uniqueness_of :email, :message => "already in use"

  has_many :customers, dependent: :delete
  has_many :charges, dependent: :delete
  has_many :charge_imports, dependent: :delete
  has_many :customer_imports, dependent: :delete
  has_many :sde_imports, dependent: :delete
  has_many :cde_imports, dependent: :delete

  has_many :trends 

  # cohort
  has_one  :cohort, dependent: :delete, autobuild: true

  embeds_one   :account
  embeds_one   :stat, autobuild: true

  attr_accessible :provider, :uid, :name, :email, :livemode, :token, :token_expires
  attr_accessor :password

  index({ email: 1 }, { unique: true, background: true })
  index({ api_token: 1 }, { unique: true, background: true })

  before_create :generate_api_token
  after_create  :schedule_imports
  before_save   :encrypt_password


  def self.create_with_omniauth(auth)
    new_user = {provider:auth['provider'], uid:auth['uid']}
    if auth['info']
      new_user["livemode"] = auth['info']['livemode'] || false
    end
    if auth['credentials']
      new_user["token"]         = auth['credentials']['token'] || ''
      new_user["token_expires"] = auth['credentials']['expires'] || true
    end
    User.create! new_user
  end

  def self.authenticate email, password
    user = where(:email => email).first
    if user && user.saved_password == password
      user
    else
      nil
    end
  end


  def add_trends
    # Overview
    trends << Trend.new(type:"mrr",group:"overview",name:"Total MRR",
                             desc:"Monthly recuring revenue",
                             unit:"amount",source:"charges",interval:'month',
                             p_criteria:{"amount"=>"$amount"}, 
                             m_criteria:{"created"=>{"$ne"=>nil},"paid"=>true},
                             groupby_ts:%Q|created|)

    # MRR
    trends << Trend.new(type:"new_mrr",group:"mrr",name:"New MRR",
                             desc:"Monthly recuring revenue from new customers",
                             unit:"amount",source:"charges",interval:'month',
                             p_criteria:{"amount"=>"$amount"}, 
                             m_criteria:{"created"=>{"$ne"=>nil},"paid"=>true,"new_mrr"=>true},
                             groupby_ts:%Q|created|)

    trends << Trend.new(type:"failed_mrr",group:"lost",name:"Failed Charges",
                             desc:"Failing monthly recuring revenue from new customers",
                             unit:"amount",source:"charges",interval:'month',
                             p_criteria:{"amount"=>"$amount"}, 
                             m_criteria:{"paid"=>false},
                             groupby_ts:%Q|created|)

    trends << Trend.new(type:"failed_mrr_by_country",group:"mrr",name:"Failed MRR by countries",
                             desc:"Failing monthly recuring revenue from new customers",
                             unit:"amount",source:"charges",interval:'month',
                             p_criteria:{"amount"=>"$amount","country"=>"$card.country"}, 
                             m_criteria:{"paid"=>false},
                             groupby_ts:%Q|created|,dimension:'country')

    trends << Trend.new(type:"failed_mrr_by_cc_type",group:"mrr",name:"Failed MRR by card type",
                             desc:"Failing monthly recuring revenue from new customers",
                             unit:"amount",source:"charges",interval:'month',
                             p_criteria:{"amount"=>"$amount","card_type"=>"$card.card_type"}, 
                             m_criteria:{"paid"=>false},
                             groupby_ts:%Q|created|,dimension:'card_type')

    trends << Trend.new(type:"churn_mrr",group:"mrr",name:"Churn MRR",
                             desc:"The lost monthly recuring revenue from churning customers in the current month", 
                             unit:"amount",source:"customers",interval:'month',
                             p_criteria:{"amount"=>"$subscription.plan.amount"},
                             m_criteria:{"canceled_at"=>{"$ne"=>nil}},
                             groupby_ts:%Q|canceled_at|) 

    # CHURN METRICS
    trends << Trend.new(type:"new_cust",group:"churn",name:"# of new Customers",
                             desc:"# new of customers in the current month}", 
                             unit:"count",source:"customers",interval:'month',
                             p_criteria:{"customers" => 1}, 
                             m_criteria:{},
                             groupby_ts:%Q|created|)

    trends << Trend.new(type:"churn_cust",group:"churn",name:"# of churned  Customers",
                             desc:"# of churned customers in the current month}", 
                             unit:"count",source:"customers",interval:'month',
                             p_criteria:{"customers" => 1}, 
                             m_criteria:{"canceled_at"=>{"$ne"=>nil}},
                             groupby_ts:%Q|canceled_at|)
  end

  def saved_password
    @saved_password ||= BCrypt::Password.new(self.password_hash)
  end

  def encrypt_password
    if password.present?
    @saved_password = BCrypt::Password.create(password)
    self.password_hash = @saved_password
    self.password = nil
    end
  end

  def refresh_data
    add_trends if self.trends.empty?

    # get the timestamp of the last imported object
    last_charge_import   = self.charge_imports.asc(:start_at).last.start_at
    last_customer_import = self.customer_imports.asc(:start_at).last.start_at
    last_cde_import      = self.cde_imports.asc(:start_at).last.start_at
    last_sde_import      = self.sde_imports.asc(:start_at).last.start_at
    # schedule new imports    
    self.charge_imports.create(  start_at:Time.now,end_at:last_charge_import,token:self.token,limit:MAX_IMPORTS)        
    self.customer_imports.create(start_at:Time.now,end_at:last_customer_import,token:self.token,limit:MAX_IMPORTS)
    self.cde_imports.create(     start_at:Time.now,end_at:last_cde_import,token:self.token,limit:MAX_IMPORTS)        
    self.sde_imports.create(     start_at:Time.now,end_at:last_sde_import,token:self.token,limit:MAX_IMPORTS)        
  end

  def refresh_metrics
    self.revenue_metric.refresh!
    self.lost_revenue_metric.refresh!
    self.acquisition_metric.refresh!
    self.cancellation_metric.refresh!
  end

  def refresh_metrics20
    (self.churn_mrr_metric.nil? ? self.churn_mrr_metric : self.churn_mrr_metric).refresh!
    (self.new_mrr_metric.nil? ? self.create_new_mrr_metric : self.new_mrr_metric).refresh!
  end

  def refresh_cohorts
    self.cohort.refresh!
  end

  def schedule_imports
    begin
      self.charge_imports.create(start_at:Time.now,end_at:BEGINING_OF_TIME,token:self.token,limit:MAX_IMPORTS)        
      self.customer_imports.create(start_at:Time.now,end_at:BEGINING_OF_TIME,token:self.token,limit:MAX_IMPORTS)
      self.cde_imports.create(start_at:Time.now,end_at:BEGINING_OF_TIME,token:self.token,limit:MAX_IMPORTS)        
      self.sde_imports.create(start_at:Time.now,end_at:BEGINING_OF_TIME,token:self.token,limit:MAX_IMPORTS)              
    rescue Exception => e
      logger.error "YYY: failed to schedule imports for users #{self._id}\n#{e.message}"
    end
  end


  protected 

  def generate_api_token 
    self.api_token = loop do
      random_token = SecureRandom.urlsafe_base64
      break random_token unless User.where(api_token: random_token).exists?
    end
  end


end

base/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def edit
    @user = User.find(params[:id]) if params[:id]
    @user ||= current_user
  end
  
  def update
    plan = params[:user][:plan] unless params[:user][:plan].nil?
    params[:user] = params[:user].except(:plan)
    if current_user.update_attributes(params[:user])
      current_user.update_plan(plan) unless plan.nil?
      redirect_to account_path, :notice => "You successfully updated your account!"
    else
      redirect_to account_path, :alert => "Ops ... we couldn\'t update your account!\n #{current_user.errors.full_messages.join}"
    end
  end

  def upgrade_from_trial
    plan_status = current_user.update_plan(params[:plan]) if params[:plan].present?
    current_user.stripe_token = params[:stripe_token]
    if plan_status && current_user.save
      redirect_to account_path, :notice => "You successfully updated your account!"
    else
      redirect_to upgrading_path, :alert => "Ops ... we couldn\'t update your account!\n #{current_user.errors.full_messages.join}"
    end
  end

  def update_plan
    plan = params[:user][:plan] unless params[:user][:plan].nil?
    if current_user.update_plan(plan) && current_user.save
      redirect_to account_path, :notice => "You successfully updated your plan!"
    else
      redirect_to account_path, :alert => "Ops ... we couldn\'t update your account!\n #{current_user.errors.full_messages.join}"
    end
  end

  def destroy
    @user = User.find(params[:id]) if params[:id]
    @user ||= current_user
    @user.destroy
    redirect_to :root
  end

end

base/app/views/users/_cancel.html.haml
%p 
  Canceling your account will delete all your data on StripeMetrics.com. 
  Canceling your account will also end your subscription to StripeMetrics.com.
%p  
  This action is not reversible.
  = simple_form_for @user,:url => { :action => "destroy" }, :html => {:method => :delete } do |f|
    - if notification = f.error_notification
      .alert.alert-error.fade.in
        %a.close{"data-dismiss" => "alert", :href => "#"} ×
        = notification
    .form-actions
      .pull-right
        = f.button :submit, 'Cancel my account',:class => 'btn btn-danger'

base/app/views/users/_edit_plan.html.haml
#plan-options.row-fluid
	.box.span10
		= simple_form_for current_user, :url => update_plan_path, :html => {:method => :put, :class => 'form-horizontal' } do |f|
		  .modal-body
		    = f.input :plan, :collection => User.available_plans, :as => :radio_buttons, :label_method => lambda {|t| t.titleize}, :label => false, :item_wrapper_class => 'inline'
		  .modal-footer
		    = f.submit "Change Plan", :class => "btn btn-primary"

base/app/views/users/_plan_alert.html.haml
.row-fluid
  .alert.span12
    %h4 You're still on the free trial
    %p 
    You have #{distance_of_time_in_words(Time.now,current_user.created_at+7.days)} to upgrade your account.

base/app/views/users/_user.html.haml
= simple_form_for @user, :validate => true do |f|
  - if notification = f.error_notification
    .alert.alert-error.fade.in
      %a.close{"data-dismiss" => "alert", :href => "#"} ×
      = notification
  = f.input :email, :hint => "this is also your username (1)" ,:wrapper => :prepend, :label => false do
    = content_tag :span, "Email", :class => "add-on"
    %span.add-on>
      %i.icon-envelope
    = f.input_field :email
    %a#email_missing{:href => "#", :rel => "popover"}
  = f.input :password,:hint => "leave empty to keep the same (2)", :wrapper => :prepend, :label => false do
    = content_tag :span, "password", :class => "add-on"
    = f.input_field :password
  = f.input :api_token,:hint => "" ,:wrapper => :prepend, :label => false do
    = content_tag :span, "Api Token (3)", :class => "add-on"
    = f.input_field :api_token, :disabled => true
  .form-actions
    .pull-right
      = f.button :submit, 'Update',:class => 'btn-primary'

.text-info
  (1) email is required to upgrade and email reports.
  %br
  (2) email and password are required to run the command line tool.
  %br
  (3) API token is used by the command line tool and to authenticate API requests.

  :javascript
    $(function() {
      var highlight_if_no_val=function () {
        var options = {
                title : '<div style="text-align:center; color:red; font-size:14px;"> Hey! </div>',
                html :true,
                content : '<div class="text-info">We need your email (1).</div>' 
          }
        $('#email_missing').popover(options)  
        !$(this).val() ? $('#email_missing').popover('show') : $('#email_missing').popover('hide');
      }
      $('#user_email').keyup(highlight_if_no_val).each(highlight_if_no_val);
    });

base/app/views/users/edit.html.haml
- if current_user.in_free_trial?
  = render "plan_alert"
  .row-fluid
    .box.span6
      .box-header
        %h2
          %i.halflings-icon.tasks
          = succeed "Your Credentials" do
            %span.break
      .box-content
        = render "user"
    .box.span6
      .box-header
        %h2
          %i.halflings-icon.tasks
          = succeed "Confidentiality" do
            %span.break
      .box-content
        %p Your email is never shared with anyone, period. 
        %p We need your email for two reasons:
        %ul
          %li to email you reports if you have selected that option
          %li so we can identify you when you use the command line tool
    .box.span6
      .box-header
        %h2
          %i.halflings-icon.tasks
          = succeed "Cancel your account" do
            %span.break
      .box-content
        = render "cancel"        

- else
  = render 'edit_plan'

/       .row
/         .span6
/           .widget
/             .widget-header
/               %i.icon-user
/               %h3 Your Credentials
/             .widget-content
/               = render 'user'
/         .span6
/           .widget.widget-box
/             .widget-header
/               %i.icon-info-sign
/               %h3 Confidentiality
/             .widget-content
/               %p Your email is never shared with anyone, period. 
/               %p We need your email for two reasons:
/               %ul
/                 %li to email you reports if you have selected that option
/                 %li so we can identify you when you use the command line tool
/           .widget.widget-box
/             .widget-header
/               %i.icon-warning-sign
/               %h3 Cancel your account
/             .widget-content
/               = render 'cancel'
              
/ .row-fluid.sortable
/   .box.span12

/   .box.span12
/     .box-header{"data-original-title" => ""}
/       %h2
/         %i.halflings-icon.edit
/         = succeed "Form" do
/           %span.break
/       .box-icon
/         %a.btn-setting{href: "#"}
/           %i.halflings-icon.wrench
/         %a.btn-minimize{href: "#"}
/           %i.halflings-icon.chevron-up
/         %a.btn-close{href: "#"}
/           %i.halflings-icon.remove
/     .box-content
/       %form.form-horizontal
/         %fieldset
/           .control-group
/             %label.control-label{for: "focusedInput"} Focused input
/             .controls
/               %input#focusedInput.input-xlarge.focused{type: "text", value: "This is focused…"}/
/           .control-group
/             %label.control-label Uneditable input
/             .controls
/               %span.input-xlarge.uneditable-input Some value here
/           .control-group
/             %label.control-label{for: "disabledInput"} Disabled input
/             .controls
/               %input#disabledInput.input-xlarge.disabled{disabled: "disabled", placeholder: "Disabled input here…", type: "text"}/
/           .control-group
/             %label.control-label{for: "optionsCheckbox2"} Disabled checkbox
/             .controls
/               %label.checkbox
/                 %input#optionsCheckbox2{disabled: "disabled", type: "checkbox", value: "option1"}/
/                 This is a disabled checkbox
/           .control-group.warning
/             %label.control-label{for: "inputWarning"} Input with warning
/             .controls
/               %input#inputWarning{type: "text"}/
/               %span.help-inline Something may have gone wrong
/           .control-group.error
/             %label.control-label{for: "inputError"} Input with error
/             .controls
/               %input#inputError{type: "text"}/
/               %span.help-inline Please correct the error
/           .control-group.success
/             %label.control-label{for: "inputSuccess"} Input with success
/             .controls
/               %input#inputSuccess{type: "text"}/
/               %span.help-inline Woohoo!
/           .control-group
/             %label.control-label{for: "selectError3"} Plain Select
/             .controls
/               %select#selectError3
/                 %option Option 1
/                 %option Option 2
/                 %option Option 3
/                 %option Option 4
/                 %option Option 5
/           .control-group
/             %label.control-label{for: "selectError"} Modern Select
/             .controls
/               %select#selectError{"data-rel" => "chosen"}
/                 %option Option 1
/                 %option Option 2
/                 %option Option 3
/                 %option Option 4
/                 %option Option 5
/           .control-group
/             %label.control-label{for: "selectError1"} Multiple Select / Tags
/             .controls
/               %select#selectError1{"data-rel" => "chosen", multiple: "multiple"}
/                 %option Option 1
/                 %option{selected: "selected"} Option 2
/                 %option Option 3
/                 %option Option 4
/                 %option Option 5
/           .control-group
/             %label.control-label{for: "selectError2"} Group Select
/             .controls
/               %select#selectError2{"data-placeholder" => "Your Favorite Football Team", "data-rel" => "chosen"}
/                 %option{value: ""}
/                 %optgroup{label: "NFC EAST"}
/                   %option Dallas Cowboys
/                   %option New York Giants
/                   %option Philadelphia Eagles
/                   %option Washington Redskins
/                 %optgroup{label: "NFC NORTH"}
/                   %option Chicago Bears
/                   %option Detroit Lions
/                   %option Green Bay Packers
/                   %option Minnesota Vikings
/                 %optgroup{label: "NFC SOUTH"}
/                   %option Atlanta Falcons
/                   %option Carolina Panthers
/                   %option New Orleans Saints
/                   %option Tampa Bay Buccaneers
/                 %optgroup{label: "NFC WEST"}
/                   %option Arizona Cardinals
/                   %option St. Louis Rams
/                   %option San Francisco 49ers
/                   %option Seattle Seahawks
/                 %optgroup{label: "AFC EAST"}
/                   %option Buffalo Bills
/                   %option Miami Dolphins
/                   %option New England Patriots
/                   %option New York Jets
/                 %optgroup{label: "AFC NORTH"}
/                   %option Baltimore Ravens
/                   %option Cincinnati Bengals
/                   %option Cleveland Browns
/                   %option Pittsburgh Steelers
/                 %optgroup{label: "AFC SOUTH"}
/                   %option Houston Texans
/                   %option Indianapolis Colts
/                   %option Jacksonville Jaguars
/                   %option Tennessee Titans
/                 %optgroup{label: "AFC WEST"}
/                   %option Denver Broncos
/                   %option Kansas City Chiefs
/                   %option Oakland Raiders
/                   %option San Diego Chargers
/           .form-actions
/             %button.btn.btn-primary{type: "submit"} Save changes
/             %button.btn Cancel
/   / /span
/ / /row