base/config/routes.rb
Stripemetrics::Application.routes.draw do
	
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin'                  => 'sessions#new',     :as => :signin
  match '/signout'                 => 'sessions#destroy', :as => :signout
  match '/auth/failure'            => 'sessions#failure'

  # =============== HOME ============================================
  match 'quickstart'          => 'home#quickstart',:as => :quickstart
  match 'faq'                 => 'home#faq',       :as => :faq
  match 'about'               => 'home#about',     :as => :about

  # =============== USER ============================================
  match 'account'              => 'users#edit',               :as => :account
  match 'cancel'               => 'users#destroy',            :as => :cancel
  match '/users/update'        => 'users#update',             :as => :user_update
  match 'upgrade_from_trial'   => 'users#upgrade_from_trial', :as => :upgrade_from_trial
  match 'update_plan'          => 'users#update_plan',        :as => :update_plan

  # =============== PLANS ===========================================
  match 'plans'                => 'plans#index',   :as => :pricing
  match 'upgrading'            => 'plans#index_for_upgrading',   :as => :upgrading

  # =============== RESOURCES ============================================
  get '/trends/:id/source',  to: 'trends#source'
  resources :trends, :only => [:show, :index]

  # =============== OTHER ============================================
  match 'dashboard'        => 'dashboard#index',:as => :dashboard
  match 'cohort'           => 'cohorts#index',:as => :cohort
  match 'status'           => 'imports#index',:as => :status

  # match 'jobs'                     => 'jobs#index',      :as => :jobs      
  # match 'jobs/:action'             => 'jobs#action'

  root :to => "home#quickstart"
  resources :users, :only => [:index, :show, :edit, :update ]

  mount Resque::Server, :at => "/rescousse"  

end

base/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @max_data_points = 12
    @mrr          = current_user.trends.where(type:'mrr').first
    @new_mrr      = current_user.trends.where(type:'new_mrr').first
    @failed_mrr   = current_user.trends.where(type:'failed_mrr').first
    @new_cust     = current_user.trends.where(type:'new_cust').first
    @churn_cust   = current_user.trends.where(type:'churn_cust').first

    @charge_imports     = current_user.charge_imports
    @customer_imports   = current_user.customer_imports
    @sde_imports        = current_user.sde_imports
    @cde_imports        = current_user.cde_imports

  end

end

base/app/helpers/dashboard_helper.rb
module DashboardHelper

  def trailing_30_days_volume
    if current_user.paid_charge_volume_trend.monthly.empty?
      '<div class="icon-question-sign"></div>'
    else
      number_to_currency(current_user.paid_charge_volume_trend.monthly.last[1], precision: 0)
    end    
  end

  def trailing_30_days_volume_desc
    if current_user.paid_charge_volume_trend.monthly.empty? || current_user.paid_charge_volume_trend.monthly.size < 2
     'not enough data'
    else
      this_month = current_user.paid_charge_volume_trend.monthly.last[1]
      last_month = current_user.paid_charge_volume_trend.monthly[-2][1]
      if this_month < last_month
        "<i class=\"icon-arrow-down text-error\"> Monthly Revenue is down from #{ number_to_currency(last_month, precision: 0)}</i>"
      else  
        "<i class=\"icon-arrow-up text-success\"> Monthly Revenue is up from #{ number_to_currency(last_month, precision: 0)}</i>"                   
      end
    end
  end

  def trailing_30_days_acquisition
    if current_user.acquisition_trend.monthly.empty?
      '<div class="icon-question-sign"></div>'
    else
      current_user.acquisition_trend.monthly.last[1]
    end    
  end

  def trailing_30_days_acquisition_desc
    if current_user.acquisition_trend.monthly.empty? || current_user.acquisition_trend.monthly.size < 2
     'not enough data'
    else
      this_month = current_user.acquisition_trend.monthly.last[1]
      last_month = current_user.acquisition_trend.monthly[-2][1]
      if this_month < last_month
        "<i class=\"icon-arrow-down text-error\"> Monthly new users is down from #{last_month}</i>"
       else  
        "<i class=\"icon-arrow-up text-success\"> Monthly new users is up from #{last_month}</i>"
      end
    end
  end

  def trailing_30_days_cancellation
    if current_user.cancellation_trend.monthly.empty?
      '<div class="icon-question-sign"></div>'
    else
      current_user.cancellation_trend.monthly.last[1]
    end    
  end

  def trailing_30_days_cancellation_desc
    if current_user.cancellation_trend.monthly.empty? || current_user.cancellation_trend.monthly.size < 2   
     'not enough data'
    else
      this_month = current_user.cancellation_trend.monthly.last[1]
      last_month = current_user.cancellation_trend.monthly[-2][1]
      if this_month < last_month
        "<i class=\"icon-arrow-down text-success\"> Monthly cancellation is down from #{last_month}</i>"
       else  
        "<i class=\"icon-arrow-up text-error\"> Monthly cancellation is up from #{last_month}</i>"
      end
    end
  end

  def trailing_30_failed_charges
    if current_user.failed_charge_volume_trend.monthly.empty?
      '<div class="icon-question-sign"></div>'
    else
      number_to_currency(current_user.failed_charge_volume_trend.monthly.last[1], precision: 0)
    end    
  end

  def trailing_30_failed_charges_desc
    if current_user.failed_charge_volume_trend.monthly.empty? || current_user.failed_charge_volume_trend.monthly.size < 2
      'not enough data'
    else
      this_month = current_user.failed_charge_volume_trend.monthly.last[1]
      last_month = current_user.failed_charge_volume_trend.monthly[-2][1]
      if this_month < last_month
        "<i class=\"icon-arrow-down text-success\"> Monthly failed charges is down from #{number_to_currency(last_month, precision: 0)}</i>"
       else  
        "<i class=\"icon-arrow-up text-error\"> Monthly failed charges is up from #{number_to_currency(last_month, precision: 0)}</i>"
      end
    end
  end

end

base/app/views/dashboard/_bigstats.html.haml
.row-fluid
  .span3.statbox.purple{ondesktop: "span3", ontablet: "span6"}
    .boxchart=@new_mrr.as_bigstat_data
    .number
      =@new_mrr.tsm_average
      %i{class:(@new_mrr.tsm_average > 0 ? 'icon-arrow-up' : 'icon-arrow-down')}
    .title=@new_mrr.name
    .footer
      = link_to "read full report", trend_path(@new_mrr)
  .span3.statbox.green{ondesktop: "span3", ontablet: "span6"}
    .boxchart=@failed_mrr.as_bigstat_data
    .number
      =@failed_mrr.tsm_average
      %i{class:(@failed_mrr.tsm_average > 0 ? 'icon-arrow-up' : 'icon-arrow-down')}
    .title=@failed_mrr.name
    .footer
      =link_to 'read full report', trend_path(@failed_mrr)
  .span3.statbox.blue.noMargin{ondesktop: "span3", ontablet: "span6"}
    .boxchart=@new_cust.as_bigstat_data
    .number
      =@new_cust.tsm_average
      %i{class:(@new_cust.tsm_average > 0 ? 'icon-arrow-up' : 'icon-arrow-down')}
    .title=@new_cust.name
    .footer
      =link_to 'read full report', trend_path(@new_cust)
  .span3.statbox.yellow{ondesktop: "span3", ontablet: "span6"}
    .boxchart=@churn_cust.as_bigstat_data
    .number
      =@churn_cust.tsm_average
      %i{class:(@churn_cust.tsm_average > 0 ? 'icon-arrow-up' : 'icon-arrow-down')}
    .title=@churn_cust.name
    .footer
      =link_to 'read full report', trend_path(@churn_cust)

base/app/views/dashboard/_chart.html.haml
.widget
  .widget-header
    %i.icon-star
    %h3=title
  .widget-content
    .chart-holder{:id=> div}

:javascript
  var chart = new Highcharts.Chart({
      chart: {
          renderTo: "#{div}",
          alignTicks: false,
          zoomType: 'x',
          spacingRight: 20
      },
      title: {text:'#{title}'},
      subtitle: {
          text: document.ontouchstart === undefined ?
              'Click and drag in the plot area to zoom in' :
              'Drag your finger over the plot to zoom in'
      },
      xAxis: {
          type: 'datetime',
          maxZoom: 14 * 24 * 3600000, // fourteen days
          title: {
              text: null
          }
      },
      yAxis: {
          title: {
              text: '#{title}'
          }
      },
      tooltip: {
          //pointFormat: '{series.name} produced <b>{point.y:,.0f}</b><br/>warheads in {point.x}'
          shared: true
      },
      legend: {
          enabled: false
      },
      plotOptions: {
          series: {
              marker: {
                  enabled: false
              }
          },
          area: {
              lineWidth: 1,
              marker: {
                  enabled: false,
                  symbol: 'circle',
                  radius: 2,
                  states: {
                      hover: {
                          enabled: true
                      }
                  }
              },
              shadow: false,
              states: {
                  hover: {
                      lineWidth: 1
                  }
              },
              threshold: null
          }
      },
      series: [{
          type: 'areaspline',
          name: '#{(title || 'Chart')}',
          pointInterval: 24 * 3600 * 1000,
          pointStart: #{start || Time.now.to_i},
          data: #{data || []}
      }]
  });

base/app/views/dashboard/_import_status.html.haml
.row-fluid.hideInIE8.circleStats
  .span2{ondesktop: "span2", ontablet: "span4"}
    .circleStatsItemBox.yellow
      .header Customer Data Import 
      %span.percent percent
      .circleStat
        %input.whiteCircle{type: "text", value: "58"}/
      .footer
        %span.count
          %span.number 20000
          %span.unit MB
        %span.sep /
        %span.value
          %span.number 50000
          %span.unit MB

base/app/views/dashboard/_imports.html.haml
.row-fluid.hideInIE8.circleStats
  = render "/imports/stats", title: "Customer Imports", 
          imports: @customer_imports, type: 'CustomerImport', color:"yellow"
  = render "/imports/stats", title: "Charges Imports",
          imports: @charge_imports, type: 'ChargeImport', color:"green"
  = render "/imports/stats", title: "Churn Imports",
          imports: @cde_imports, type: 'CdeImport', color:"greenDark"
  = render "/imports/stats", title: "Subscription Imports",
          imports: @sde_imports, type: 'SdeImport', color:"orange"

base/app/views/dashboard/_index1.html.haml
.main
  .main-inner
    .container
      .row
        .span12
          = render "bigstats"
      .row
        .span6
          = render "stock_chart_v1", :title  => "Revenue",
                            :data   => @paid_charges.daily,
                            :start  => @paid_charges.start_date,
                            :div    => "paid_charges_trend_chart",
                            :type   => 'paid_charge_volume_trend',
                            :unit   => '$'
        .span6    
          = render "stock_chart_v1", :title  => "Failed Charges",
                            :data   => @failed_charges.daily,
                            :start  => @failed_charges.start_date,
                            :div    => "failed_charges_trend_chart",
                            :type   => 'failed_charge_volume_trend',
                            :unit   => '$'
      .row
        .span6
          = render "stock_chart_v1", :title => 'New Users',
                            :data   => @customers.daily,
                            :start  => @customers.start_date,
                            :div    => "customers_trend_chart",
                            :type   => 'acquisition_trend',
                            :unit   => ''
        .span6
          = render "stock_chart_v1", :title => 'Cancellation',
                            :data   => @cancelations.daily,
                            :start  => @cancelations.start_date,
                            :div    => "cancelations_trend_chart",
                            :type   => 'cancellation_trend',
                            :unit   => ''

base/app/views/dashboard/_index2.html.haml
.main
  .main-inner
    .container
      .row
        .span6
          = render "/charts/overview_chart", 
                  :title  => "Monthly Revenue",
                  :icon   => "icon-thumbs-up",
                  :object => @paid_charges,
                  :data   => @paid_charges.as_highchart_data,
                  :start  => @paid_charges.start_date,
                  :div    => "paid_charges_trend_chart",
                  :type   => 'column',
                  :ylabel => %Q{'$' + ((this.value>1000) ? (this.value/1000 +'k') : (this.value))},
                  :ttunit => '$'
        .span6    
          = render "/charts/overview_chart", :title  => "Failed Charges",
                  :object => @failed_charges,
                  :icon   => "icon-thumbs-down",
                  :data   => @failed_charges.as_highchart_data,
                  :start  => @failed_charges.start_date,
                  :div    => "failed_charges_trend_chart",
                  :type   => 'column',
                  :ylabel => %Q{'$' + ((this.value>1000) ? (this.value/1000 +'k') : (this.value))},
                  :ttunit => '$'
      .row
        .span6
          = render "/charts/overview_chart", :title => 'New Users',
                  :object => @customers,
                  :icon   => "icon-thumbs-up",
                  :data   => @customers.as_highchart_data,
                  :start  => @customers.start_date,
                  :div    => "customers_trend_chart",
                  :type   => 'area',
                  :ylabel => %Q{this.value},
                  :ttunit => ''
        .span6
          = render "/charts/overview_chart", :title => 'Cancellation',
                  :object => @cancelations,
                  :icon   => "icon-thumbs-down",
                  :data   => @cancelations.as_highchart_data,
                  :start  => @cancelations.start_date,
                  :div    => "cancelations_trend_chart",
                  :type   => 'area',
                  :ylabel => %Q{this.value},
                  :ttunit => ''

base/app/views/dashboard/_mrrs_and_trends.html.haml
.row-fluid
  .span8.widget.blue{ondesktop: "span8", ontablet: "span7"}
    =render '/charts/two_series_as_bars', 
            bar: @mrr, line: @failed_mrr, max_data_points: @max_data_points 
  .sparkLineStats.span4.widget.green{ondesktop: "span4", ontablet: "span5"}
    %ul.unstyled
      %li
        %span.sparkLineStats3
        Total Revenue:
        %span.number 781
      %li
        %span.sparkLineStats4
        Average Revenue:
        %span.number 2,19
      %li
        %span.sparkLineStats5
        Avg. Visit Duration:
        %span.number 00:02:58
      %li
        %span.sparkLineStats6
        Bounce Rate:
        %span.number 59,83%
      %li
        %span.sparkLineStats7
        \% New Visits:
        %span.number 70,79%
      %li
        %span.sparkLineStats8
        \% Returning Visitor:
        %span.number 29,21%
    .clearfix

base/app/views/dashboard/_sparkline.html.haml
%p
  .text-success #{title}
  .dynamicsparkline{:id=> div}
:javascript
  $(document).ready(function() {
    jQuery('##{div}').sparkline(#{data}, {type: 'line',lineColor: '#000000', fillColor: '#ff7f00'});    
  });

base/app/views/dashboard/_stock_chart.html.haml
.widget
  .widget-header
    %i.icon-star
    %h3=title
  .widget-content
    .chart-holder{:id=> div}

:javascript
  var groupingUnits = [[
    'week',                         // unit name
    [1]                             // allowed multiples
  ], [
    'month',
    [1, 2, 3, 4, 6]
  ]];

  var chart = new Highcharts.StockChart({
      chart: {
          renderTo: "#{div}",
          alignTicks: false
      },

      rangeSelector: {
          selected: 3
      },

      yAxis: [{
          title: {
              text: 'Count'
          },
          height: 250,
          lineWidth: 2
      }, {
          title: {
              text: 'Volume'
          },
          top: 300,
          height: 100,
          offset: 0,
          lineWidth: 2
      }],
      
      series: [{
          type: 'spline',
          name: 'Count',
          data: #{data},
          dataGrouping: {
            units: groupingUnits
          }
      }]
  });

base/app/views/dashboard/_stock_chart_v1.html.haml
.widget
  .widget-header
    %i.icon-star
    %h3=title
    .btn-group{"data-toggle" => "buttons-radio"}
      %button.btn{:id=> "#{div}_day"} Dy
      %button.btn{:id=> "#{div}_week"} Wk
      %button.btn{:id=> "#{div}_month"} Mo
  .widget-content
    .chart-holder{:id=> div}

:javascript

  var #{div} = new Highcharts.StockChart({
    chart : {
      renderTo : "#{div}"
    },
    rangeSelector : {
      selected : 1,
      inputEnabled : false
    },

    navigator : {
      height : 30
    },

    xAxis : {
      maxZoom : 14 * 24 * 3600000 // fourteen days
    },

    series : [{
      name : "#{title}",
      data : #{data || []},
      tooltip : {
        yDecimals : 4
      }
    }]
  });

  $("##{div}_day").click(function() {
    $.ajax({
    type: "GET",
    url: "#{trends_path}",
    data: {"type": "#{type}","group_by": "daily"},
    dataType: 'json',
    success: function(data){
          #{div}.series[0].setData(data);
      }
    });
  });
  $("##{div}_week").click(function() {
    $.ajax({
    type: "GET",
    url: "#{trends_path}",
    data: {"type": "#{type}","group_by": "weekly"},
    dataType: 'json',
    success: function(data){
          #{div}.series[0].setData(data);
      }
    });
  });
  $("##{div}_month").click(function() {
    $.ajax({
    type: "GET",
    url: "#{trends_path}",
    data: {"type": "#{type}","group_by": "monthly"},
    dataType: 'json',
    success: function(data){
          #{div}.series[0].setData(data);
      }
    });
  });

base/app/views/dashboard/_two_charts.html.haml
.widget
  .widget-header
    %i.icon-star
    %h3=title
  .widget-content
    .chart-holder{:id=> div}

:javascript
  var chart = new Highcharts.Chart({
      chart: {
          renderTo: "#{div}",
          alignTicks: false,
          zoomType: 'x',
          spacingRight: 20,
          type:"areaspline"
      },
      title: {text:'#{title}'},
      subtitle: {
          text: document.ontouchstart === undefined ?
              'Click and drag in the plot area to zoom in' :
              'Drag your finger over the plot to zoom in'
      },
      xAxis: {
          type: 'datetime',
          maxZoom: 14 * 24 * 3600000, // fourteen days
          title: {
              text: null
          }
      },
      yAxis: {
          title: {
              text: '#{title}'
          }
      },
      tooltip: {
          shared: true,
          valueSuffix: "#{unit}"
      },
      legend: {
          enabled: false
      },
      plotOptions: {
          area: {
              fillColor: {
                  linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
                  stops: [
                      [0, Highcharts.getOptions().colors[0]],
                      [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                  ]
              },
              lineWidth: 1,
              marker: {
                  enabled: false
              },
              shadow: false,
              states: {
                  hover: {
                      lineWidth: 1
                  }
              },
              threshold: null
          }
      },
      plotOptions: {
          area: {
              stacking: 'normal',
              lineColor: '#666666',
              lineWidth: 1,
              marker: {
                  lineWidth: 1,
                  lineColor: '#666666'
              }
          }
      },      
      series: #{series}
  });

base/app/views/dashboard/index.html.haml
= render "bigstats"
= render "mrrs_and_trends"
= render "imports"

= content_for :modal do
  #myModal.modal.hide.fade
    .modal-header
      %button.close{"data-dismiss" => "modal", type: "button"} ×
      %h3 Settings
    .modal-body
      %p Here settings can be configured...
    .modal-footer
      %a.btn{"data-dismiss" => "modal", href: "#"} Close
      %a.btn.btn-primary{href: "#"} Save changes
  .clearfix