base/config/routes.rb
Stripemetrics::Application.routes.draw do
	
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin'                  => 'sessions#new',     :as => :signin
  match '/signout'                 => 'sessions#destroy', :as => :signout
  match '/auth/failure'            => 'sessions#failure'

  # =============== HOME ============================================
  match 'quickstart'          => 'home#quickstart',:as => :quickstart
  match 'faq'                 => 'home#faq',       :as => :faq
  match 'about'               => 'home#about',     :as => :about

  # =============== USER ============================================
  match 'account'              => 'users#edit',               :as => :account
  match 'cancel'               => 'users#destroy',            :as => :cancel
  match '/users/update'        => 'users#update',             :as => :user_update
  match 'upgrade_from_trial'   => 'users#upgrade_from_trial', :as => :upgrade_from_trial
  match 'update_plan'          => 'users#update_plan',        :as => :update_plan

  # =============== PLANS ===========================================
  match 'plans'                => 'plans#index',   :as => :pricing
  match 'upgrading'            => 'plans#index_for_upgrading',   :as => :upgrading

  # =============== RESOURCES ============================================
  get '/trends/:id/source',  to: 'trends#source'
  resources :trends, :only => [:show, :index]

  # =============== OTHER ============================================
  match 'dashboard'        => 'dashboard#index',:as => :dashboard
  match 'cohort'           => 'cohorts#index',:as => :cohort
  match 'status'           => 'imports#index',:as => :status

  # match 'jobs'                     => 'jobs#index',      :as => :jobs      
  # match 'jobs/:action'             => 'jobs#action'

  root :to => "home#quickstart"
  resources :users, :only => [:index, :show, :edit, :update ]

  mount Resque::Server, :at => "/rescousse"  

end

base/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    redirect_to :dashboard if user_signed_in? 
  end

	def quickstart
    redirect_to :dashboard if user_signed_in? 
	end

  def faq
  end

  def pricing
  end

end

base/app/helpers/home_helper.rb
# encoding: UTF-8 
module HomeHelper
  def stripe_connect_help
    <<-EOF
      Easily and securely connect your account in just a couple of clicks. 
      You don’t need to share private keys—after a single click for authorization we can start aggregating your Stripe data.</p>
      Learn more at https://stripe.com/connect 
    EOF
  end
end

base/app/views/home/_benefits.html.haml
.row
  .span4#benefit1
    .widget
      .widget-header
        %i.icon-heart
        %h3 Zero Configuration
      .widget-content
        %p.text
          Learn about your business and act on your metrics in a matter of minutes.
          %br
          We start data imports and aggregation automaticaly, as soon as you connect with your Stripe account.
  .span4#benefit2
    .widget
      .widget-header
        %i.icon-bar-chart
        %h3 Actionnable Metrics
      .widget-content
        %p.text
          No vanity metrics here!
          %br
          Metrics and tools that you - the developer - can laverage to identify issues and act !
          %br
  .span4#benefit3
    .widget
      .widget-header
        %i.icon-wrench
        %h3 Command Line
      .widget-content
        %p.text
          We provide beautifull charts for your CEO. 
          %br
          For you - the developer - we provide a command line interface and an API.
          %br
          So you can generate reports or list of customers with failed charges from the confort of your terminal.

base/app/views/home/_pitch.html.haml
.hero-unit
  %h1 Metrics & Analytics for Stripe
  %p 
  Revenue, Customer Acquisition, Churn rates, trends and cohort analysis - out of the box.
  %p
  %a.btn.btn-danger.btn-large.pull-right{:href => "#{signin_path}"}
    %i.icon-white.icon-thumbs-up
    Connect with Stripe and try - risk free !

base/app/views/home/about.html.haml
.main
  .main-inner
    .container
      .row
        .span8
          .widget
            .widget-header
              %i.icon-thumbs-up
              %h3 Our Story
            .widget-content
              StripeMetrics was born as a response to a comment on a Hacker News post about the greatness of Stripe and the lack of analytics it provided. This was our Light Bulb moment..!
              %br
              = image_tag("y18.gif")
              = link_to('Simple SaaS Metrics Dashboard for Stripe','https://news.ycombinator.com/item?id=4439874')
          .widget
            .widget-header
              %i.icon-group
              %h3 Meet the team
            .widget-content
              %i.icon-linkedin-sign
              = link_to 'Yacin Bahi, PhD., Founder', 'https://www.linkedin.com/in/yacinbahi/' 
              %br
              Yacin founded StripeMetrics in 2013 our of necessity. As a passionate Stripe developer, Yacin needed a way to easily generate actionable reports from Stripe data.  

base/app/views/home/faq.html.haml
.row-fluid
  .box.span8
    .box-header
      %i.icon-pushpin
      %h3 Frequently Asked Questions
    .box-content
      %ol.faq-list
        %li
          %h4 Is my data secure ?
          %p We have read-only access to your Stripe account. We only import data that is used to agregate trends. We don't store your customer information for example, data that we store is quantitative rather than quantitative. 
        %li   
          %h4 Is my data kept confidential ?
          %p We don't know who you are or what company you're representing. If your anonymity is important to you. make sure you to use a anonymous email address when registering.
        %li
          %h4 How long does the first import take ?
          %p It depends on how much data we have to import. It varies from a couple of minutes to a couple of hours. Imports are incremental and partial data and trends are available within 1 to 2 minutes.
        %li
          %h4 How do I connect my account with Stripe ?
          %p Use the "Connect with Stripe" link. This will sign you up as well as connect your account on StripeMetrics with your Stripe account. This will give us read-only access to your Stripe data.
        %li
          %h4 Are you affiliated with Stripe Inc. ?
          %p No, we are not affiliated with Stripe Inc., but we love what they do and we love metrics !
        %li
          %h4 What metrics are available ?
          %p Customer trends, including acquisition and cancellation. Transaction volume trends, by number, volume and TSM (trailing six month compound average).
          Anything missing, email us and we'll add it to the dashboard.
        %li
          %h4 What metrics will be released soon ?
          %p Customer trends, including acquisition and churn. Transaction volume trends, by number and volume. Projected monthly revenue, revenue last 30 trailing days and more. Anything missing, email us and we'll add it to the dashboard.
        %li
          %h4 A command line interface, really ?
          %p We're geeks and programmers and we love the command line. Visit 
          %a{:href => "http://yacc.github.io/stripemetrics-cli/"} stripemetrics-cli Github page
          for more information.
        %li
          %h4 How do I install the command line interface ?
          %p The command line interface is a Ruby gem. 
          .pre.code
            gem 'stripemetrics-cli', :git => 'git://github.com/yacc/stripemetrics-cli.git'
  .box.span4
    .box-content
      %a.btn.btn-large.btn-warning.btn-support-ask{:href => "http://support.stripemetrics.com/support/solutions"} Contact Support
      %a.btn.btn-large.btn-support-contact{:href => "http://support.stripemetrics.com/support/discussions"} Ask the Crowd

base/app/views/home/index.html.haml
#content.span10
  .row-fluid

base/app/views/home/quickstart.html.haml
.main
  .main-inner
    .container
      = render "/home/pitch"
      = render "/home/steps/three_steps"
      = render "/home/benefits"